INSERT INTO CARGO (CARGO_NOME) VALUES ('Tecnico');
INSERT INTO CARGO (CARGO_NOME) VALUES ('Analista');
INSERT INTO CARGO (CARGO_NOME) VALUES ('Gerente');
INSERT INTO CARGO (CARGO_NOME) VALUES ('Chefe de Departamento');

INSERT INTO DEPARTAMENTO (DEPARTAMENTO_NOME) VALUES ('Financeiro');
INSERT INTO DEPARTAMENTO (DEPARTAMENTO_NOME) VALUES ('Marketing');
INSERT INTO DEPARTAMENTO (DEPARTAMENTO_NOME) VALUES ('TI');

INSERT INTO FUNCIONARIO (FUNCIONARIO_NAME, FUNCIONARIO_AGE, FUNCIONARIO_BIRTHDAY, FUNCIONARIO_DOCUMENT, CARGO_ID, DEPARTAMENTO_ID)
VALUES ('Nome-Funcionario', '30', '1990-06-07', '11223344', 2, 3);

INSERT INTO FUNCIONARIO_DEPARTAMENTO VALUES (1, 1);
INSERT INTO FUNCIONARIO_DEPARTAMENTO VALUES (1, 3);